version: "3"
services:
  retailApp:
    container_name: retailApp
    image: retail
    ports:
      - "9002:9002"
    networks:
      - network-retail
    depends_on:
      - externalRetail
      - redis
 
  externalRetail:
    container_name: externalRetail
    image: retail-external
    ports:
      - "8080:8080"
    networks:
      - network-retail

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
     - ./redisData:/data
    networks:
      - network-retail

networks:
  network-retail:

volumes:
  redisData: